version: '2.1'
volumes:
  db_volume:

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "store"
    ports:
      - "3306:3306"
    volumes:
      - /mysql:/var/lib/mysql
     
  apiserver:
    image: api
    restart: always
    environment:
      - DB_USER=root
      - DB_PASS=root1234
      - DB_SERVER=127.0.0.1
      - DB_PORT=3306
      - DB_NAME=store
      - DB_DRIVER=mysqld
      - TOKEN_KEY=keyforjwtencrypt
      - TOKEN_TIME=24
    
    ports:
      - 8081:8081
    links:
      - mysql      
  
      
    